### ISSUE TITLE
Provide stackit-cert-manager-webhook via Helm-Repository

### ISSUE THREAD

**Issue by FabianKlemmAA** [stackitcloud/stackit-cert-manager-webhook#40]
### Is your feature request related to a problem? Please describe.

When using the `stackit-cert-manager-webhook` in a Helm chart as dependency, we cannot use a link to a Github release.

### Describe the solution you'd like

It would be great if the helm charts could be provided in a helm repository (e.g. via Gtihub pages), so that a helm Chart.yaml such as
```
apiVersion: v2
name: cert-manager-deps
version: 0.1.0
description: Deploying external-dns to manage DNS records with Stackit webhook container
dependencies:
  - name: stackit-cert-manager-webhook
    version: 0.2.0
    repository: https://stackitcloud.github.io/stackit-cert-manager-webhook
```
would work

### Describe alternatives you've considered

At this moment, we have to download the build chart as .tgz file (or all chart files) and put it in the /charts directory (still this causes issue, e.g. when updating via helm.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
